# Generated by Django 5.2.13 on 2026-04-16 01:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='project',
            name='projects_pr_status_f023cb_idx',
        ),
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
        migrations.AddField(
            model_name='project',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_cancelled'], name='projects_pr_is_canc_471ac5_idx'),
        ),
    ]
