# Generated by Django 5.2.13 on 2026-04-14 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='facebook_profile',
            field=models.URLField(blank=True, null=True),
        ),
    ]
