# Generated by Django 5.2.13 on 2026-04-18 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0004_alter_user_options_user_email_verification_sent_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="failed_delete_attempts",
            field=models.IntegerField(default=0),
        ),
    ]
