# Generated by Django 5.2.13 on 2026-04-14 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.ImageField(blank=True, help_text='Optional icon shown on the homepage category list', null=True, upload_to='categories/')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'db_table': 'categories_category',
                'ordering': ['name'],
            },
        ),
    ]
